"""
Shared test fixtures for {{project_name}}.
Generated by Rally Tavern python-pytest-harness.
"""
import os
import pytest
from unittest.mock import MagicMock


# --- Configuration ---

@pytest.fixture(scope="session")
def test_config():
    """Test configuration overrides."""
    return {
        "TESTING": True,
        "DEBUG": False,
        "DATABASE_URL": os.getenv("TEST_DATABASE_URL", "sqlite:///:memory:"),
    }


# --- Database Fixtures ---

@pytest.fixture(scope="function")
def db_session(test_config):
    """
    Provide a clean database session per test.
    Override this fixture in your project's conftest.py to use your ORM.

    Example (SQLAlchemy):
        @pytest.fixture
        def db_session(test_db_engine):
            connection = test_db_engine.connect()
            transaction = connection.begin()
            session = SessionLocal(bind=connection)
            yield session
            session.close()
            transaction.rollback()
            connection.close()
    """
    yield MagicMock()


# --- HTTP Client Fixtures ---

@pytest.fixture
def client():
    """
    HTTP test client.
    Override in your project's conftest.py for your framework.

    Example (FastAPI):
        @pytest.fixture
        def client(app):
            return TestClient(app)

    Example (Flask):
        @pytest.fixture
        def client(app):
            return app.test_client()
    """
    yield MagicMock()


# --- Factory Fixtures ---

class Factory:
    """
    Base factory for creating test data.
    Subclass and register factories for your models.

    Usage:
        class UserFactory(Factory):
            model = User
            defaults = {"name": "Test User", "email": "test@example.com"}
    """
    model = None
    defaults = {}
    _counter = 0

    @classmethod
    def create(cls, session=None, **overrides):
        """Create an instance with defaults merged with overrides."""
        cls._counter += 1
        data = {**cls.defaults, **overrides}
        if cls.model is None:
            return data
        instance = cls.model(**data)
        if session is not None:
            session.add(instance)
            session.flush()
        return instance

    @classmethod
    def build(cls, **overrides):
        """Build an instance without persisting."""
        data = {**cls.defaults, **overrides}
        if cls.model is None:
            return data
        return cls.model(**data)

    @classmethod
    def reset(cls):
        cls._counter = 0


@pytest.fixture
def factory():
    """Factory base class for creating test data."""
    Factory.reset()
    return Factory
